### PR TITLE
Experiment: count small batch of ngrams at a time

### PR DESCRIPTION
**Pull request by jelmervdl**
New idea:
1. only read a small batch of ngrams at a time
2. count these specifically in all documents _that follow the batch we just read_
3. merge the ones `> 1` in the long term `df`
4. seek back to the end of the last batch we read, and continue to the next batch of ngrams

Good properties:
- `df` doesn't grow massive with singletons
- we control the batch size, so the number of singletons we keep in memory: more predictable memory behaviour
- determined to finish

Bad properts:
- We read the input files many times (or about ~5 in my tests)

### CODE REVIEW

**Comment by jelmervdl** [comment]
Okay, hear me out.

1. We add `Save()` and `Restore()` methods to `FilePiece` that give us a way to seek to a previously known state of the reader, including decompression state and mmap offsets.
2. First, this allows us to faster seek back to the position we were at when we want to read the next batch of ngrams.
3. But second, if we have these restore points at regular intervals, we can have N readers, each starting at a different restore point, and read until the next restore point. We can do *parallel decompression*! We just have to read the entire file once to get the restore points we need.

**Comment by jelmervdl** [comment]
I also tried using thread-local hashmaps (6b03a872771f9a4494f5995a0e962c5570f259b5) but that didn't seem to be a good idea. So far, using a hashmap for selecting the ngrams, and then thread-specific fixed-size vectors for tracking the counts for each ngram seems to be the fastest.

Trying to finish `mt` with this version now, and see whether I made something stable. I think I can double the 50m limit on LUMI to be honest (running with 16 threads, ~30gb mem as there's no benefit of having more cpus dedicated to this program)

**Comment by jelmervdl** [comment]
… so this has been running in production for HPLT, I deem it working okay enough to merge.

**Comment by akutuzov** [comment]
@jorgtied @onadegibert should we merge this pull request?

**Comment by jorgtied** [comment]
> @jorgtied @onadegibert should we merge this pull request?

I have no opinion about this.

**Comment by akutuzov** [comment]
But who is now the main person responsible for `docalign`? :)

**Comment by onadegibert** [comment]
I have no idea who is the new responsible person, but I think we can merge this request to update the link in the paper.

**Comment by akutuzov** [comment]
Will you do it @onadegibert ?

**Comment by onadegibert** [comment]
done!

**Pull request merged**
